language: node_js
sudo: false
node_js:
- iojs
- '7'
install:
- yarn install
script:
- yarn test
env:
  secure: IxtY5LSF03exUIyLRQYR5QH+4NWJM6tS/9aP9QStHENJJ51Nm2aGhCo60YLVw2AKTwSSjcO+IHB32iqY3ql1GPR5USIBdvuEpfJ1V6fKMmHN/AA0CLb6zUXH86SeWAqUV4MfBfUXRrcItW9c9qNYdBGZJJ329hLDd3TTMOH4pWD4AmFXwzKTOFJ63IR4PnS2VSrT98NlHA9a70xKtmf7ac0cx2i2UQ0ZcZKcAsWyTEPGju2/SwCNPsATb5CzeB97YL55Ubd2UUt33o7KIEMBfFkhB2UbMJubFHwia78d5x9ty2fSGBKDsOjkRMM27DkC8TRp7IjyvpKCogWZuTyeMwKUIkZR3teNsG+PqD1qU23yWiRkFJWZCk3TdgGmSvZfZCAj2qJbW76lY9KZrhQGQVaqWUCe4ldYfBVErM5dd7IkFIKk7Wn/RyQapUfc3Rl9NNwhKxcy84/bKZuriGTxriGLHc+F66xuYMU4sh2a33DID6Qj/VK/cVySU5KHYMYd2hDhipNSExqAxPF/rG7Y1+z59z0Y6h8bgCZDsT0PQOpXgp/pjlAhvnv3Jjj+i5ut5a/Fsxw7/zybLEKVT7Xbd9FsZPbnks7Kd1bneHFyPtcipCNciOS+WWVwxs/s0tc5bmj+/zG2v21y/j8i4AoFTLfxlrf9gq1hxgz0YkF/Asg=
